version: "3"

services:
  backend:
    container_name: onecrm_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5050:5050
    # depends_on:
    #   - db
    network_mode: "host"
    # networks:
    #   - onecrm-network 
      
    
  frontend:
    container_name: onecrm_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    network_mode: "host"
    # networks:
    #   - onecrm-network  

  # db:
#     image: postgres:15.1
#     container_name: onecrm_db
#     ports:
#       - 5432:5432
#     environment:
#       POSTGRES_DB: tii_products
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 1234
#       PGDATA: /var/lib/postgresql/data/pgdata
#     # volumes:
#     #   - pgdata:/var/lib/postgresql/data/
#     volumes:
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#     # networks:
#     #   - onecrm-network  
#     network_mode: "host"
#     restart: always
# volumes:
#   pgdata:
  
# networks:
#   onecrm-network:
#     driver: bridge
#     name: onecrm-network
